<a href="https://colab.research.google.com/github/deehzee/mlgym/blob/main/d2l/pytorch/ch02/2_preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ch2: Preliminaries

## 2.1: Data Minipulation

### 2.1.1: Getting Started

In [1]:
!python --version

Python 3.12.13


In [2]:
import torch
torch.__version__

'2.10.0+cpu'

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [22]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X.numel()

12

In [24]:
X.shape

torch.Size([3, 4])

In [25]:
x.reshape(-1, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
x.reshape(3, -1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
x.reshape(-1, 3) == x.reshape(4, -1)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

In [28]:
x.reshape((3, 4))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [30]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [32]:
torch.randn(3, 4) # standard normal

tensor([[-0.8567,  1.1006, -1.0712,  0.1227],
        [-0.5663,  0.3731, -0.8920, -1.5091],
        [ 0.3704,  1.4565,  0.9398,  0.7748]])

In [33]:
torch.randn((3, 4))

tensor([[ 0.1919,  1.2638, -1.2904, -0.7911],
        [-0.0209, -0.7185,  0.5186, -1.3125],
        [ 0.1920,  0.5428, -2.2188,  0.2590]])

In [34]:
torch.manual_seed(0)
torch.randn((3, 4))

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])

In [35]:
torch.manual_seed(0)
torch.randn(3, 4)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])

In [36]:
torch.tensor([[1, 2, 4, 3], [3, 1, 0, -1], [3, 2, 0, 3]])

tensor([[ 1,  2,  4,  3],
        [ 3,  1,  0, -1],
        [ 3,  2,  0,  3]])

### 2.1.2: Indexing and Slicing

In [37]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [38]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [39]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [41]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.3: Operations

In [42]:
x

tensor([12., 12., 12., 12., 12., 12., 12., 12.,  8.,  9., 10., 11.])

In [43]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [44]:
x = torch.tensor([1., 2, 3, 4])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x % y, x ** y

(tensor([3., 4., 5., 6.]),
 tensor([-1.,  0.,  1.,  2.]),
 tensor([2., 4., 6., 8.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([1., 0., 1., 0.]),
 tensor([ 1.,  4.,  9., 16.]))

In [46]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2., 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [47]:
torch.cat((X, Y), dim=-1), torch.cat((X, Y), dim=-2)

(tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]))

In [48]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [64]:
X.sum()

tensor(66.)

In [68]:
X.sum().item()

66.0

In [67]:
scalar_tensor = torch.tensor(66.)
scalar_value = scalar_tensor.item()
print(f"The scalar tensor: {scalar_tensor}")
print(f"The extracted scalar value: {scalar_value}")
print(f"Type of extracted value: {type(scalar_value)}")


The scalar tensor: 66.0
The extracted scalar value: 66.0
Type of extracted value: <class 'float'>


In [70]:
import numpy as np

# PyTorch scalar extraction
scalar_tensor = torch.tensor(66.)
scalar_value_torch = scalar_tensor.item()
print(f"PyTorch tensor: {scalar_tensor}, Extracted value (torch): {scalar_value_torch}, Type: {type(scalar_value_torch)}")

# NumPy scalar extraction
numpy_array = np.array(66.)
scalar_value_numpy = numpy_array.item()
print(f"NumPy array: {numpy_array}, Extracted value (numpy): {scalar_value_numpy}, Type: {type(scalar_value_numpy)}")

# For 1D array with single element, you can also use indexing for NumPy
numpy_array_1d = np.array([66.])
scalar_value_numpy_1d = numpy_array_1d[0].item() # or just numpy_array_1d[0]
print(f"1D NumPy array: {numpy_array_1d}, Extracted value (numpy 1d): {scalar_value_numpy_1d}, Type: {type(scalar_value_numpy_1d)}")

print("\nBoth .item() methods convert a single-element tensor/array to a standard Python scalar.")

PyTorch tensor: 66.0, Extracted value (torch): 66.0, Type: <class 'float'>
NumPy array: 66.0, Extracted value (numpy): 66.0, Type: <class 'float'>
1D NumPy array: [66.], Extracted value (numpy 1d): 66.0, Type: <class 'float'>

Both .item() methods convert a single-element tensor/array to a standard Python scalar.
