<a href="https://colab.research.google.com/github/deehzee/mlgym/blob/main/d2l/pytorch/ch02/2_preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ch2: Preliminaries

## 2.1: Data Minipulation

### 2.1.1: Getting Started

In [2]:
!python --version

Python 3.12.13


In [3]:
import torch
torch.__version__

'2.10.0+cpu'

In [4]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
X.numel()

12

In [9]:
X.shape

torch.Size([3, 4])

In [10]:
x.reshape(-1, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
x.reshape(3, -1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
x.reshape(-1, 3) == x.reshape(4, -1)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

In [13]:
x.reshape((3, 4))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
torch.randn(3, 4) # standard normal

tensor([[ 1.3027,  1.3622, -0.1331, -0.6092],
        [-0.2809, -1.8206,  1.3456, -2.1644],
        [-0.5569, -0.2268, -0.5024, -0.1168]])

In [18]:
torch.randn((3, 4))

tensor([[ 0.0448,  0.9825, -0.3113, -0.0791],
        [ 0.2591, -2.1592,  1.3320,  0.4446],
        [-1.5681,  1.3284,  1.0085,  0.0439]])

In [19]:
torch.manual_seed(0)
torch.randn((3, 4))

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])

In [20]:
torch.manual_seed(0)
torch.randn(3, 4)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])

In [21]:
torch.tensor([[1, 2, 4, 3], [3, 1, 0, -1], [3, 2, 0, 3]])

tensor([[ 1,  2,  4,  3],
        [ 3,  1,  0, -1],
        [ 3,  2,  0,  3]])

### 2.1.2: Indexing and Slicing

In [22]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [24]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [25]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.3: Operations

In [27]:
x

tensor([12., 12., 12., 12., 12., 12., 12., 12.,  8.,  9., 10., 11.])

In [28]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [29]:
x = torch.tensor([1., 2, 3, 4])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x % y, x ** y

(tensor([3., 4., 5., 6.]),
 tensor([-1.,  0.,  1.,  2.]),
 tensor([2., 4., 6., 8.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([1., 0., 1., 0.]),
 tensor([ 1.,  4.,  9., 16.]))

In [30]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2., 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [31]:
torch.cat((X, Y), dim=-1), torch.cat((X, Y), dim=-2)

(tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]))

In [32]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [33]:
X.sum()

tensor(66.)

In [34]:
X.sum().item()

66.0

In [35]:
scalar_tensor = torch.tensor(66.)
scalar_value = scalar_tensor.item()
print(f"The scalar tensor: {scalar_tensor}")
print(f"The extracted scalar value: {scalar_value}")
print(f"Type of extracted value: {type(scalar_value)}")


The scalar tensor: 66.0
The extracted scalar value: 66.0
Type of extracted value: <class 'float'>


In [36]:
import numpy as np

# PyTorch scalar extraction
scalar_tensor = torch.tensor(66.)
scalar_value_torch = scalar_tensor.item()
print(f"PyTorch tensor: {scalar_tensor}, Extracted value (torch): {scalar_value_torch}, Type: {type(scalar_value_torch)}")

# NumPy scalar extraction
numpy_array = np.array(66.)
scalar_value_numpy = numpy_array.item()
print(f"NumPy array: {numpy_array}, Extracted value (numpy): {scalar_value_numpy}, Type: {type(scalar_value_numpy)}")

# For 1D array with single element, you can also use indexing for NumPy
numpy_array_1d = np.array([66.])
scalar_value_numpy_1d = numpy_array_1d[0].item() # or just numpy_array_1d[0]
print(f"1D NumPy array: {numpy_array_1d}, Extracted value (numpy 1d): {scalar_value_numpy_1d}, Type: {type(scalar_value_numpy_1d)}")

print("\nBoth .item() methods convert a single-element tensor/array to a standard Python scalar.")

PyTorch tensor: 66.0, Extracted value (torch): 66.0, Type: <class 'float'>
NumPy array: 66.0, Extracted value (numpy): 66.0, Type: <class 'float'>
1D NumPy array: [66.], Extracted value (numpy 1d): 66.0, Type: <class 'float'>

Both .item() methods convert a single-element tensor/array to a standard Python scalar.


### 2.1.4: Broadcasting

In [37]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [38]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.5: Saving Memory (In-place Vs Copies)

In [39]:
# Y += 2 (In-place)
before = id(Y)
Y += 2
after = id(Y)
before == after

True

In [40]:
# Y = Y + 2 (makes a copy)
before = id(Y)
Y = Y + 2
after = id(Y)
before == after

False

In [41]:
# Y[:] = Y + 2 (to ensure in-place operation)
before = id(Y)
Y[:] = Y + 2
after = id(Y)
before == after

True

In [42]:
# In general
Y = Y + X    # copy
Y += X       # in-place
Y[:] = Y + X # in-place

In [47]:
# numpy
import numpy as np
A = X.numpy()
before = id(A)
A += 2
after = id(A)
before == after

True

In [48]:
# numpy
before = id(A)
A = A + 2
after = id(A)
before == after

False

In [49]:
# numpy
before = id(A)
A[:] = A + 2
after = id(A)
before == after

True

In [50]:
# numpy
before = id(A)
A = np.exp(A)
after = id(A)
before == after

False

In [52]:
# pytorch
before = id(Y)
Y = torch.exp(Y)
after = id(Y)
before == after

False

In [53]:
# pytorch
before = id(Y)
Y += torch.exp_(Y)
after = id(Y)
before == after

True

### 2.1.6: Conversion to Other Python Objects

In [43]:
A = X.numpy() # convert to numpy array
B = torch.from_numpy(A) # convert from numpy array
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [45]:
# Convert a scalar tensor to a python scalar value
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [46]:
type(a), type(a.item()), type(float(a)), type(int(a))

(torch.Tensor, float, float, int)

### 2.1.7: Key Differences in the API form Numpy

### 2.1.7: Key Differences in the API from Numpy

While PyTorch's API is heavily inspired by NumPy, especially for tensor manipulation, there are several key differences to be aware of:

1.  **Dimension Specification**: PyTorch operations typically use the `dim` argument to specify the dimension(s) along which an operation should occur (e.g., `torch.sum(tensor, dim=0)`). In contrast, NumPy uses `axis` for the same purpose (e.g., `numpy.sum(array, axis=0)`).

2.  **Device Agnosticism**: PyTorch tensors can seamlessly operate on different hardware devices, such as CPUs or GPUs. This allows for easy acceleration of computations by moving tensors to a GPU (`tensor.to('cuda')`). NumPy arrays are strictly CPU-bound.

3.  **Automatic Differentiation**: A fundamental difference for deep learning is PyTorch's built-in support for automatic differentiation (Autograd). PyTorch tensors can track their computation history (via the `grad_fn` attribute) and compute gradients with respect to parameters, which is crucial for training neural networks. NumPy arrays do not offer this capability natively.

4.  **In-place Operations**: PyTorch often uses a trailing underscore convention for in-place operations (e.g., `tensor.add_(other)` modifies `tensor` directly). While NumPy also has in-place operations (e.g., `array += other`), PyTorch's explicit naming helps distinguish between operations that return a new tensor and those that modify the original in-place.

5.  **Data Types**: While both support a range of data types, PyTorch tensors are often type-sensitive for operations, and operations between tensors of different types might require explicit casting. PyTorch also has specific data types (e.g., `torch.float32`, `torch.int64`) that align with its deep learning backend.

Understanding these differences is crucial when transitioning between the two libraries or when trying to adapt NumPy code to PyTorch.