<a href="https://colab.research.google.com/github/deehzee/mlgym/blob/main/dlpy/02_mathematical_building_blocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2: Mathematical Building Blocks of Neural Networks

## A First Look at Neural Networks

In [1]:
from keras.datasets import mnist

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [5]:
train_images.shape, train_images.dtype

((60000, 28, 28), dtype('uint8'))

In [6]:
test_images.shape, test_images.dtype

((10000, 28, 28), dtype('uint8'))

In [7]:
train_labels.shape, train_labels.dtype

((60000,), dtype('uint8'))

In [8]:
test_labels.shape, test_labels.dtype

((10000,), dtype('uint8'))

In [9]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [10]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [20]:
import keras
from keras import layers

keras.backend.backend()

'tensorflow'

In [12]:
model = keras.Sequential(
    [
        layers.Dense(512, activation='relu'),
        layers.Dense(10, activation='softmax'),
    ]
)

In [13]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'],
)

In [14]:
train_images = train_images.reshape((train_images.shape[0], -1)).astype('float32') / 255
test_images = test_images.reshape((test_images.shape[0], -1)).astype('float32') / 255

(train_images.shape, train_images.dtype), (test_images.shape, test_images.dtype)

(((60000, 784), dtype('float32')), ((10000, 784), dtype('float32')))

In [15]:
train_loss, train_acc = model.evaluate(train_images, train_labels)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.1254 - loss: 2.3283
Train accuracy: 0.1250,  Train loss: 2.3281


In [16]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.8708 - loss: 0.4593
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9661 - loss: 0.1175
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9783 - loss: 0.0721
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.9856 - loss: 0.0487
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.9896 - loss: 0.0362


In [17]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([2.2504933e-07, 2.7455908e-07, 2.3131486e-05, 3.9360631e-04,
       4.1928566e-10, 4.2615666e-06, 2.1824606e-10, 9.9956292e-01,
       8.5958118e-06, 6.9639691e-06], dtype=float32)

In [21]:
predictions[0].argmax()

np.int64(7)

In [22]:
predictions[0][7]

np.float32(0.9995629)

In [23]:
test_labels[0]

np.uint8(7)

In [24]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9759 - loss: 0.0762
